### ISSUE TITLE
CLJS output too large

### ISSUE THREAD

**Issue by thheller** [noprompt/meander#84] opened 2019-10-14 21:30 UTC
I wanted to try `meander` in a CLJS project but the amount of code it adds just makes this impractical. ~430KB after `:advanced` before gzip, without using a single thing, just importing the main namespace. From a quick glance through the codebase it seems that most of the code is actually just related to the macros and not used at runtime. All this code is still in the CLJS portions of the output and since it uses multimethods it cannot be eliminated by `:advanced` compilation.

It is hard for me to tell which parts of the code are actually used at runtime but based on a macroexpand of a very simple match I see no runtime specific code at all.

```
> (macroexpand-1 '(meander.match.epsilon/match {} {:user ?name} ?name))
(clojure.core/let [TARGET__64363 {}] (clojure.core/let [VAL__64364 (.valAt TARGET__64363 :user)] (clojure.core/let [?name VAL__64364] ?name)))
```

So assuming that most of the code is actually just called at macro-expansion time with only very little parts of it used at runtime using CLJC is probably more of a burden than anything. It seems like the obvious way to get this working in CLJS but really isn't the most optimal (not even for self-hosted, if that is a requirement).

I wrote a [blog post](https://code.thheller.com/blog/shadow-cljs/2019/10/12/clojurescript-macros.html) about CLJS macros last weekend and will probably write a follow up post about CLJC in particular since this project is a pretty good example of why it is dangerous to use CLJC too much.

Of course I might be totally off and all this code is actually required at runtime but I don't believe that it is.

If there is any interest in "shrinking" the CLJS output I can provide some guidance. I think this library is really cool but I can't justify adding so many bytes to my JS output to use it.

**Comment by noprompt** [comment] 2019-10-14 21:43
> If there is any interest in "shrinking" the CLJS output I can provide some guidance.

@thheller I am absolutely interested, yes! 😄

**Comment by thheller** [comment] 2019-10-14 21:54
Ok, that is good to hear. :)

Judging by how you have organized the code the runtime related code seems already to be isolated in the `*.runtime` namespaces? Those are pretty much the only files that need to be `.cljc`. All the other files could just be `.clj`. The `meander.epsilon` ns should likely be `.clj` and have a corresponding  `.cljs` file that just does

```
(ns meander.epsilon
  (:require-macros [meander.epsilon]))
```

Since all of the related code seems to be macros with no actual API functions? It may wany to require the "runtime" namespaces though.

**Comment by noprompt** [comment] 2019-10-14 21:57
@thheller I think the problem likely has something to do with parsing code thats meant to be usable from the three platforms (JVM, JS, and Self-Hosted). The parser is designed to be extensible via `defsyntax` which defines code which registers a syntax expander that the parser can resolve. See [here](https://github.com/noprompt/meander/blob/epsilon/src/meander/syntax/epsilon.cljc#L285-L340), [here](https://github.com/noprompt/meander/blob/epsilon/src/meander/syntax/epsilon.cljc#L663-L681), and [here](https://github.com/noprompt/meander/blob/epsilon/src/meander/syntax/epsilon.cljc#L1932-L2008). The problem is particularly gross.

**Comment by thheller** [comment] 2019-10-14 22:03
From the looks of it those are quasi-macros? Are they called at runtime or in macro-expansion?

The current implemention looks like it wouldn't work with caching at all?

**Comment by noprompt** [comment] 2019-10-14 22:12
@thheller The parser is designed to be able to be run outside of macro-expansion but, primarily, the use of it will be at macro-expansion time.

> The current implemention looks like it wouldn't work with caching at all?

From the looks of this ticket, it seems like no? 😄 

I might be off on this one, but if there's a use of parsing at runtime then I'm guessing it'll prevent DCL from happening.

**Comment by jimmyhmiller** [comment] 2019-10-15 04:01
@thheller Thanks so much for this report. It was super thorough and helpful.

We can definitely reduce this quite a lot. I was about to get it down to 144KB with some quick and dirty `#?(:clj)`s thrown in.  We will most likely be dropping cljc at some point though and can hopefully get that even smaller still.

If you have any magic number in your head about what size is too big or feels good definitely let us know.

Expect to see some progress on this front this week.

**Comment by thheller** [comment] 2019-10-15 10:10
Don't think there is a magic number to reach. It all depends on your requirements and how much "bytes" you are willing to pay for the convenience you get. Good start though!

One thing you should definitely avoid importing is `cljs.pprint` since it also isn't `:advanced` compatible currently and adds quite a bit on its own.

**Comment by noprompt** [comment] 2019-10-15 16:15
> One thing you should definitely avoid importing is cljs.pprint

We've taken care of that. 😄

**Comment by noprompt** [comment] 2019-10-17 05:32
@thheller I just created a new release of the project `meander/epilson 0.0.287` which should address the problem. Using the helpful tips you gave me and the reporting tool I was able to reduce to achieve the following report.

```
| Resource                                   |   Optimized |  Total % |          JS |      Source |
|--------------------------------------------+-------------+----------+-------------+-------------|
| jar | cljs/core.cljs                       |     92.7 KB |  93.16 % |      1.3 MB |    334.3 KB |
| jar | goog/math/integer.js                 |      4.5 KB |   4.52 % |     24.6 KB |     24.6 KB |
| jar | goog/base.js                         |      1.3 KB |   1.28 % |    133.6 KB |    133.6 KB |
| jar | meander/match/runtime/epsilon.cljc   |    453.0 B  |   0.46 % |     17.0 KB |      5.4 KB |
| jar | goog/string/stringbuffer.js          |    308.0 B  |   0.31 % |      2.7 KB |      2.7 KB |
| jar | goog/object/object.js                |    133.0 B  |   0.13 % |     22.2 KB |     22.2 KB |
| jar | goog/array/array.js                  |    101.0 B  |   0.10 % |     59.5 KB |     59.5 KB |
| jar | goog/string/internal.js              |     40.0 B  |   0.04 % |     12.5 KB |     12.5 KB |
```

I'm going to close the issue. If you spot anything else or if I haven't actually solved the problem here, just reopen the ticket.

**Closed as completed by noprompt** 2019-10-17 05:32 UTC

**Comment by thheller** [comment] 2019-10-17 09:04
Fantastic!
